name: cl Example
on: push
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: says Hello
        run: echo "Hello world"
  say_hi:
    runs-on: ubuntu-latest
    steps:
      - name: says Hi
        run: echo "Hi"
